### ISSUE TITLE
[Feature Request] Multi place blocks vertically

### ISSUE THREAD

**Issue by madjin** [cryptovoxels/issues#1]
We are now able to place multiple blocks horizontally which is awesome.

It would be great to be able to also do this vertically

**Comment by bnolan** [comment]
Will add this, need some keyboard modifier.

**Comment by damo1884** [comment]
CTRL + Drag?

**Comment by damo1884** [comment]
Marking as a major bug as its probably the most wanted feature outstanding

**Comment by bnolan** [comment]
Done!
