### ISSUE TITLE
Mobile build tab strange rotation

### ISSUE THREAD

**Issue by ferroresonance** [cryptovoxels/issues#10]
On mobile (android Firefox)
When you open the build tab you are rotated approx 90 degrees in one direction and must rotate yourself back to see the build tab.

**Comment by damo1884** [comment]
marking wont fix since since this is intended I believe

**Comment by damo1884** [comment]
Maybe a grab handle would be the best option?

eg. click and drag to move the menu using a drag icon in the corner

![image](https://user-images.githubusercontent.com/1332166/59007619-0ea8a900-87dc-11e9-8731-07ec1783314b.png)

**Comment by bnolan** [comment]
Fixed.
