### ISSUE TITLE
Images placed on transparent blocks

### ISSUE THREAD

**Issue by ferroresonance** [cryptovoxels/issues#11]
When an image is placed over a transparent block your view of the image is affected by your position. The image either appears in front or behind the block.
Sometimes the images is actually placed throigh the block the a position behind it

**Comment by bnolan** [comment]
Can replicate. I'm not sure if this is a `zOffset` bug, or a transparency sorting bug.

![Screen Shot 2019-07-09 at 11 17 10 AM](https://user-images.githubusercontent.com/17499/60848563-27710800-a23b-11e9-9124-c5e861c08647.png)
![Screen Shot 2019-07-09 at 11 17 13 AM](https://user-images.githubusercontent.com/17499/60848566-293acb80-a23b-11e9-82d5-9a64066487c8.png)

**Comment by bnolan** [comment]
Seems to be fixed.
