### ISSUE TITLE
Gifs are not showing properly!

### ISSUE THREAD

**Issue by mlibty** [cryptovoxels/issues#14]
Animated gifs are not loading properly...

**Comment by bnolan** [comment]
Heya, .gifs aren't supported yet - it looks like we have either parse them in javascript (slow), or turn them into a spritesheet on the image proxy server (not too bad). We'd probably limit the gifs to ~100 frames, but should be doable in the future!

**Comment by mlibty** [comment]
@bnolan Really looking forward to it, bought few properties to make a gallery, but most my NFT are gifs... Thanks!! Love this "new" world!! :)

**Comment by damo1884** [comment]
Gifs are now working closing
