### ISSUE TITLE
Cannot move text that have url links

### ISSUE THREAD

**Issue by damo1884** [cryptovoxels/issues#16]
**Steps:**

- Create a text with a url link
- Place it
- Move it

**Expected Result:**

Text is moved

**Actual Result:**

You get navigated to the link instantly without prompt and you lose your previous edits

**Workaround:**

Remove link from text before moving it. 
Move it
Add link back

**Comment by bnolan** [comment]
Fixed, thanks!

```
+++ b/src/tools/feature.ts
@@ -162,6 +162,8 @@ export default class Selector {
 
   editFeature () {
     if (this.nextMode === FeatureSelectionMode.Move) {
+      this.ui.controls.clickNerf()
+      
       this.deactivate()
 
       setTimeout(() => {
@@ -217,6 +219,8 @@ export default class Selector {
 
     feature.regenerate()
     feature.save()
+
+    this.ui.controls.clickNerf()
   }
```
