### ISSUE TITLE
[Feature Request] Edit Shortcut improvements

### ISSUE THREAD

**Issue by damo1884** [cryptovoxels/issues#17]
### Goal
 - Easier editing of objects
 - Remove the need to use the tab menu when editing many objects

-----------------------------

### Shortcuts

When the shortcut is triggered the mode stays active after each action to allow editing many items one after the other

**Enable Move clicked object mode**
- [x] Ctrl + M

**Enable Edit clicked object mode**
- [x] Ctrl + E

**Delete mode**
 - [ ] Ctrl + X

**Enable Scale clicked object mode**
- [ ] Ctrl + S

**Enable Place image mode**
- [ ] Ctrl + I

**Enable Place text mode**
- [ ] Ctrl + T

**Exit any mode**
 - [ ] Ctrl + Q

**Delete mode**
 - [ ] Ctrl + R

**Comment by bnolan** [comment]
Someone should reopen this when the HTML5 UI becomes the default. Closing for now.
