### ISSUE TITLE
Improve Move+Delete on edit object tab menu

### ISSUE THREAD

**Issue by damo1884** [cryptovoxels/issues#18]
Move these icons up higher so they are easier to click
![image](https://user-images.githubusercontent.com/1332166/57744755-62155480-767f-11e9-8c2c-f7c60bda4cbb.png)

**Comment by damo1884** [comment]
Since you can now use Ctrl+M to move this is less important


@bnolan Ctrl+X would be great for delete also

**Comment by bnolan** [comment]
Use `M` to move, or `E` to edit. Will reopen this when I have a better idea where to put the buttons. :)
