### ISSUE TITLE
Add zoom in & zoom out buttons to the map thumbnail

### ISSUE THREAD

**Issue by damo1884** [cryptovoxels/issues#19]
Currently you can only pinch zoom the map when in world. 

Add small [+] [-] buttons for  zoom in/out 

![image](https://user-images.githubusercontent.com/1332166/58303787-7b688000-7da6-11e9-901e-a0bdbaf0d8a7.png)

**Comment by bnolan** [comment]
Fixed! Thanks.

![Screen Shot 2019-07-09 at 11 14 30 AM](https://user-images.githubusercontent.com/17499/60848445-bfbabd00-a23a-11e9-95ed-119d0a2f901d.png)
