### ISSUE TITLE
images disappear depending on camera angle

### ISSUE THREAD

**Issue by damo1884** [cryptovoxels/issues#23]
looks fine at one camera angle

![image](https://user-images.githubusercontent.com/1332166/58723434-e873ab00-838e-11e9-81a6-49286903411d.png)

then if I move my mouse slightly

![image](https://user-images.githubusercontent.com/1332166/58723425-e14c9d00-838e-11e9-9349-f78d0a4c1ad5.png)

See: https://www.cryptovoxels.com/play?coords=E@206W,355S

**Comment by bnolan** [comment]
That's z-fighting. Weird that it's still happening, thought I'd solved that. Thanks for the report.

**Comment by bnolan** [comment]
Nudged this out to `-0.05` on the local z-axis - let me know if it reoccurs. Also using zOffset so weird it happens.
