### ISSUE TITLE
Cannot save colors anymore

### ISSUE THREAD

**Issue by damo1884** [cryptovoxels/issues#24]
Save parcel tile settings

![image](https://user-images.githubusercontent.com/1332166/58723711-a5fe9e00-838f-11e9-94df-272325506091.png)

Save never finishes

CORS error thrown in console

![image](https://user-images.githubusercontent.com/1332166/58723674-91baa100-838f-11e9-9991-029e7023084c.png)

**Comment by bnolan** [comment]
Sorry everyone! It was trying to hit the new node-js [image server](https://github.com/cryptovoxels/image-server).

Fixed.
