### ISSUE TITLE
[Idea] Teleport portals

### ISSUE THREAD

**Issue by damo1884** [cryptovoxels/issues#26]
Currently it is hard for users to know what are in world teleports vs links to websites.

Teleport by walking into a portal would help differentiate between the two and would remove the need to reload the page potentially. 

If you could see where it leads to that would be insane!

![image](https://user-images.githubusercontent.com/1332166/58845125-d6b03300-862e-11e9-9e8b-a3ab87e87e0c.png)

**Comment by damo1884** [comment]
This might allow rendering the view on the other side of the portal or even the users hands 

Here is an example with 2 Scenes rendered at the same time

https://www.babylonjs-playground.com/#L0IMUD#1

**Comment by bnolan** [comment]
Cool idea, will come around on this some time.
