### ISSUE TITLE
[Feature request] Parental Controls - Disable Chat from Account Settings

### ISSUE THREAD

**Issue by madjin** [cryptovoxels/issues#27]
Sometimes there's nonsense being said in the chat, click to collapse chat window will make it more safe-for-work.

**Comment by damo1884** [comment]
We have a flag on the url now to hide the chat

```
?chat=hidden
```

https://www.cryptovoxels.com/play?coords=S@471W,437N&chat=hidden

**Comment by damo1884** [comment]
It would be great if this could be enabled in my account settings to allow parental controls.

**Comment by bnolan** [comment]
Not gonna do this for now, the `?chat=hidden` will have to do for the time being. I'll tack it onto account settings when we have such a page.
