### ISSUE TITLE
Cannot move or delete NFTs from tab menu

### ISSUE THREAD

**Issue by damo1884** [cryptovoxels/issues#29]
Looks like the extra field caused it to get covered by a layer above

Maybe shorten the description text?

![image](https://user-images.githubusercontent.com/1332166/59409148-7629a000-8d6a-11e9-8572-2d90c80978bd.png)

**Comment by bnolan** [comment]
Edited the z-index to make those buttons at the top of the stack, and added a rollover highlight to show it's working.
