### ISSUE TITLE
Cannot move image due to it overlapping with itself

### ISSUE THREAD

**Issue by damo1884** [cryptovoxels/issues#3]
**Steps:**
Place an image
Try to move it slightly

**Expected:**
Image moves

**Result:**
Image cannot be placed due to it overlapping with itself.

**Comment by bnolan** [comment]
Oooh - yeah this is crazy annoying.

**Comment by bnolan** [comment]
Fixed and deployed! Need a proper refactor of the editing code, but this is fixed for now. Thanks.
