### ISSUE TITLE
New User Usability Issues

### ISSUE THREAD

**Issue by damo1884** [cryptovoxels/issues#34]
After onboarding my girlfriend in Cryptovoxels

- Add a help button to the desktop client that opens a help panel on desktop (not in world)
  - Explain WASD directional controls 
  - F enables flying (look in the direction you want to fly and walk forward)
  - Explain parcel details build/erase functions. (outline, pyramid etc)
  - How to build (tab opens menu, click to select block, click to place, click + drag to place many)
  - How to delete (hold shift (while in block place mode) and click + drag)
  - How to change colors and apply textures (with link to the parcel settings)

- Make color always available in tab menu before the parcel has any COLR. 
  - Tell users they need COLR and direct them how to get some.

- Not being able to click drag vertically seems like a bug to new users (my girlfriend is building a wall and she is doing it vertically 1 by 1 and thought not being able to build vertically was a bug)

**Comment by bnolan** [comment]
Fixed vertical drag, agree need to add instructions.

**Comment by damo1884** [comment]
Closing as this is largely fixed
