### ISSUE TITLE
[Feature Request] Ability to duplicate objects (Images, Poly Text, Audio etc)

### ISSUE THREAD

**Issue by damo1884** [cryptovoxels/issues#4]
When placing multiple identical images it is very time consuming.

Having the ability to duplicate an image that retains the same width, height, image url etc would make this much easier.

**Comment by bnolan** [comment]
Oh that's a cool idea. 👍

**Comment by damo1884** [comment]
Ctrl+C for copy?

**Comment by bnolan** [comment]
Done! Press `C` to copy.
