### ISSUE TITLE
[Bug] Can't edit features when I'm not standing on my parcel

### ISSUE THREAD

**Issue by conlan** [cryptovoxels/issues#41]
I have some images that are on the outermost wall of my parcel, but they're very hard to click on from "within" my parcel. So ideally I'd like to be able to stand on the street and edit them still.

My current workaround is to delete the block that an image is pasted on and then click to edit from inside, and then put the block back after done editing. Or to stand directly under the image (while still standing on the parcel) to edit it, but this is really clunky and hard to click sometimes.

(see images below)

**Comment by conlan** [comment]
Standing on sidewalk and can't edit image:

![Screen Shot 2019-09-16 at 12 04 26 PM](https://user-images.githubusercontent.com/79074/64985629-2cc18300-d87a-11e9-946b-8cbe1ac853bf.png)

Standing underneath image (while still standing on parcel) to edit it:

![Screen Shot 2019-09-16 at 12 03 59 PM (2)](https://user-images.githubusercontent.com/79074/64985670-3e0a8f80-d87a-11e9-88b0-7a91664b1f66.png)

**Comment by conlan** [comment]
Okay, I have discovered another work around. If I shortcut with "E" while I'm standing on the parcel I can then walk outside to click on the feature. This is easier but still would be nice if I could edit features from standing outside of it.

**Comment by mmckegg** [comment]
This should be fixed now!
