### ISSUE TITLE
[Bug] OpenSea price box always shows 0.12000 ETH

### ISSUE THREAD

**Issue by conlan** [cryptovoxels/issues#43]
Price box:
![Screen Shot 2019-09-16 at 2 47 48 PM](https://user-images.githubusercontent.com/79074/64995780-05c27b80-d891-11e9-8a0d-0b641368ffb3.png)

Actual price:
![Screen Shot 2019-09-16 at 2 47 54 PM](https://user-images.githubusercontent.com/79074/64995789-0bb85c80-d891-11e9-98a5-0d8409997d9b.png)

**Comment by bnolan** [comment]
Fixed, sorry bad bug. Will re-add price once it's accurate.
