### ISSUE TITLE
[Idea] Local vs World chat

### ISSUE THREAD

**Issue by conlan** [cryptovoxels/issues#44]
Would be cool if there was a global and local chat, where local was only in the surrounding parcels. (I suppose is lower priority since there's not a huge number of active users yet at any given time)

**Comment by mmckegg** [comment]
Chat is now a lot more localised. And we have now added a `/broadcast message` flag. 

For now, we're still seeing all messages in the world, but faded out if that person is a long way away. Maybe in the future we can hide the distant ones.

**Comment by conlan** [comment]
Nice! Yeah been seeing this now in effect.
