### ISSUE TITLE
[Idea] Build template for OpenSea item gallery

### ISSUE THREAD

**Issue by conlan** [cryptovoxels/issues#45]
It would be great if there were pre-built templates in the "Build..." dropdown that set up a simple gallery that uses the OpenSea API to look up items owned by the creator's wallet address and to populate the gallery.

This way, digital art collectors who are less interested in building/customizing their gallery but just want a place to display their collection can 1-click set it up.

**Comment by bnolan** [comment]
Oh this is a fantastic idea!

**Comment by damo1884** [comment]
We lost this ability when network requests no longer worked in parcel scripts.

Is there plans to allow fetch() in parcel scripts?

Lets close this issue and just make a general issue for making http calls in scripting

**Comment by conlan** [comment]
Sounds good!
