### ISSUE TITLE
Images transparency displays as black and white displays as transparent

### ISSUE THREAD

**Issue by damo1884** [cryptovoxels/issues#5]
**Steps:**

Add an image with transparency and some white in it.
https://www196.lunapic.com/editor/premade/transparent.gif

**Expected:**
Image has transparency and colors display correctly

![image](https://user-images.githubusercontent.com/1332166/56482057-fae8f380-6476-11e9-9ecb-9660c5a0f730.png)

**Result:**
Transparent parts become black, white becomes transparent

![image](https://user-images.githubusercontent.com/1332166/56482049-ee649b00-6476-11e9-9eb2-4a356781bdb0.png)

**Comment by bnolan** [comment]
Oh yeah! So this is sort of intentional. It's because we use a blend mode to apply textures to the wall - like so:

```js
    const material = new B.StandardMaterial('image-feature-texture', this.scene)
    material.diffuseTexture = texture
    material.alpha = 0.999
    material.alphaMode = this.description.inverted ? BABYLON.Engine.ALPHA_SCREENMODE : BABYLON.Engine.ALPHA_MULTIPLY
    material.specularColor.set(0, 0, 0)
    material.emissiveColor.set(1, 1, 1)
    material.backFaceCulling = false
    material.zOffset = -4
```

However - I think the transparent part of the image should become white, not black - then at least the transparent part will be transparent. I'll try fix this in the image server.

**Comment by bnolan** [comment]
Ok, fixed this particular bug by making the background color white instead of black. I'll open a seperate issue for being able to use transparent textures.
