### ISSUE TITLE
[Bug, P2, #Web] Not including "www" in URL times out when visiting a parcel

### ISSUE THREAD

**Issue by conlan** [cryptovoxels/issues#53]
When entering a URL it doesn't redirect if you don't include the "www" prefix:

https://www.cryptovoxels.com/play?coords=W@340W,275S <-- works
https://cryptovoxels.com/play?coords=W@340W,275S <-- doesn't work (times out)

**Comment by conlan** [comment]
This is an issue because on some platforms like Twitter they hide the www prefix and people have accidentally copied that link leading them to think that CV is broken when they paste it elsewhere:

![Screen Shot 2019-11-08 at 11 42 36 AM](https://user-images.githubusercontent.com/79074/68505761-e1de3f00-021c-11ea-90f8-8668c53c6c25.png)

**Comment by bnolan** [comment]
Fixed!
