### ISSUE TITLE
[Bug, P1, #Wearables]  Clicking "remove" on a wearable removes the wrong wearable

### ISSUE THREAD

**Issue by conlan** [cryptovoxels/issues#54]
Video:
https://share.getcloudapp.com/12uEl6Lp

**Comment by conlan** [comment]
From Edmond:

![Screen_Shot_2019-11-11_at_8 09 05_AM](https://user-images.githubusercontent.com/79074/68614896-c40c1680-0476-11ea-990b-ecce2a13e3f9.png)

**Comment by bnolan** [comment]
Fixed! Thanks for the report and video team! Was missing `key={key}` on the editors.
