### ISSUE TITLE
[Bug, P1, #Wearables] Can only equip 5 wearables

### ISSUE THREAD

**Issue by conlan** [cryptovoxels/issues#55]
Not sure if this is by design?

<img width="1113" alt="Screen Shot 2019-11-10 at 11 04 23 PM" src="https://user-images.githubusercontent.com/79074/68567776-ba4ec880-040e-11ea-9407-f5e86b1c2405.png">

**Comment by ferroresonance** [comment]
Maybe this is the same issue as the inability to scroll to older wearables. Is this a scrolling issue?

**Comment by bnolan** [comment]
Intentional for now until I can do some performance work.
