### ISSUE TITLE
[Bug, P2, #Scripting] Can't set the URL for a text item in HTML UI mode

### ISSUE THREAD

**Issue by conlan** [cryptovoxels/issues#57]
The current work around is to leave HTML mode to edit and then come back:

<img width="967" alt="Screen Shot 2019-11-10 at 11 45 37 PM" src="https://user-images.githubusercontent.com/79074/68570004-6b0b9680-0414-11ea-9db0-bc0cc7b19fb5.png">

**Comment by bnolan** [comment]
Fixed in `2.30.2`, thanks for all the reports @conlan !
