### ISSUE TITLE
[Bug, P1, #Scripting] Setting a feature ID in HTML UI mode is not saved

### ISSUE THREAD

**Issue by conlan** [cryptovoxels/issues#58]
Repro steps:
1. Start editing in HTML UI mode.
2. Click a feature.
3. Type in a feature ID.
4. click out of the feature inspector.
5. click back into feature inspector.
6. Expected feature ID to be saved.

https://share.getcloudapp.com/Z4uzNJe8

**Comment by bnolan** [comment]
Fixed in `2.23.0`.
