### ISSUE TITLE
[Feature, P2, #Scripting] Allow features to request opening an external URL on click.

### ISSUE THREAD

**Issue by conlan** [cryptovoxels/issues#59]
Currently the only way to request opening an external URL is with a Text feature. There's a workaround that people have been using to make voxels and images clickable by providing an empty text and scaling that but it would be great if there was some functionality like parcel.open(URL) to make those actually click linkable.

**Comment by conlan** [comment]
Implementing this would also reduce the number of features needed in the world since this workaround appears to have gotten quite popular.

**Comment by bnolan** [comment]
Great idea. 👍

**Comment by bnolan** [comment]
Fixed with `hyperlinks`.
