### ISSUE TITLE
Disappearing custom tiles on website

### ISSUE THREAD

**Issue by madjin** [cryptovoxels/issues#6]
Custom tiles save and you can use them in world. However, when you go back to add another custom tile the ones you added vanish.

They still appear in world and if you add a new tile and press save it saves the newly added one but removes the ones you had previously added even though they show up in world.

**Comment by bnolan** [comment]
Yup, this is a bug with the custom tile creator, it doesn't load back in your old tiles. Need to fix.

**Comment by damo1884** [comment]
Making this a major bug since it means lost work the next time you go in and edit the tiles or colors

**Comment by damo1884** [comment]
As a part of fixing this bug could we also allow copying of textures & colors from another parcel you own?

It is currently extremely hard to match textures and colors on adjacent parcels

**Comment by bnolan** [comment]
Fixed.
