### ISSUE TITLE
[Feature request] Settings gear in bottom right

### ISSUE THREAD

**Issue by madjin** [cryptovoxels/issues#66]
We were thinking there can be a settings button on the bottom right of the  UI.

![](https://cdn.discordapp.com/attachments/431671342044020749/649413937850482718/unknown.png)

There can be client [flags](https://www.cryptovoxels.com/docs/flags) and audio configurations as options. Might be useful to save the settings too, the only forseeable issue is that we may split into separate realities (day vs night, fog vs no-fog, etc).

**Comment by mmckegg** [comment]
This has now been addressed! Settings menu now in top bar!
