### ISSUE TITLE
bug #wearables the wearables screen has no scroll function, only new items can be chosen.

### ISSUE THREAD

**Issue by ferroresonance** [cryptovoxels/issues#68]
If you have mire than a certain amount of wearables minted you can onlu view the first 10 or so with no abolitu to scroll to older items in your inventory. This may be the same issue as the 5 werables limit? Is thete a limit ir id it the scroll function?

**Comment by bnolan** [comment]
Will fix thanks!

**Comment by bnolan** [comment]
Scroll fixed.

**Comment by ferroresonance** [comment]
The new scroll is fantastic and allows you easier manipulation of wearables however you still need an additional scroll bar to scroll through "available wearables" Anymore than 20 and you can only view or use the first 20

**Comment by bnolan** [comment]
Oh ok thanks I'll fix that too! :)

**Comment by bnolan** [comment]
Fixed! Increased limit to 100.

```
    fetch(`https://api.opensea.io/api/v1/assets/?limit=100&owner=${app.state.wallet}&asset_contract_address=${process.env.WEARABLE_CONTRACT_ADDRESS}`)
```
