### ISSUE TITLE
[Bug, P1, #Audio] Audio features don't playback on the first click.

### ISSUE THREAD

**Issue by conlan** [cryptovoxels/issues#69]
https://www.cryptovoxels.com/play?coords=SW@342W,311S. 

But if you click pause and try again then the second time they work.

**Comment by bnolan** [comment]
Playback seems completely broken at the moment - I'll take a look...

**Comment by conlan** [comment]
Great! Can test when a fix is back up.

**Comment by bnolan** [comment]
I believe is fixed!
