### ISSUE TITLE
Block shows as placeable at edge of parcel but is not

### ISSUE THREAD

**Issue by damo1884** [cryptovoxels/issues#7]
**Steps:**

Point to place a block at the outermost edge of a parcel before the block disapears
Click to place

**Expected Results:**
Block places

**Result:**
Block does not place

One block in from edge can be placed

Either allow placement or do not show the block as placeable where it is not.

**Comment by bnolan** [comment]
Hey @damo1884 can you give me an example URL where you're having this occur? I thought I'd fixed this bug, but it may be still around.

**Comment by damo1884** [comment]
Sorry did see this as wasn't getting notifications 

This happens on every parcel at the edges

![image](https://user-images.githubusercontent.com/1332166/58928733-93c28e00-8708-11e9-86e9-0cdf8f3c156f.png)

**Comment by damo1884** [comment]
link to example of it happening
https://www.cryptovoxels.com/play?coords=S@230W,373S

**Comment by bnolan** [comment]
Can replicate here... 

    /play?coords=E@227W,363S

![Screen Shot 2019-07-09 at 11 20 04 AM](https://user-images.githubusercontent.com/17499/60848638-86368180-a23b-11e9-8af2-41b85c38f1b3.png)

**Comment by bnolan** [comment]
It's not possible to delete that row of voxels....

**Comment by bnolan** [comment]
Fixed!

```
-      if (pos.x < 0 || pos.y < 0 || pos.z < 0) {
+      if (pos.x <= 0 || pos.y <= 0 || pos.z <= 0) {
```
