### ISSUE TITLE
[Feature, P2, #Wearables] Checkbox to "flip" wearable for left/right use.

### ISSUE THREAD

**Issue by ryanio** [cryptovoxels/issues#71]
Currently if you design a left or right handed wearable for a shoe, glove, etc. it doesn't really work well on the other side. If possible, it would be nice if there was a "flip" or "mirror" checkbox in the Wearables Config-o-matic.

**Comment by bnolan** [comment]
Fixed.

**Comment by ryanio** [comment]
i don't think i ever saw this feature surfaced in the ui :/
