### ISSUE TITLE
[Bug, P1, #NFT] NFT gifs no longer animating

### ISSUE THREAD

**Issue by conlan** [cryptovoxels/issues#72]
NFT gifs that were previously worked have stopped animating and just display their frames:

![image](https://user-images.githubusercontent.com/79074/71785878-b9bf5200-2fb9-11ea-9d0e-0e8f180fb24b.png)

![image](https://user-images.githubusercontent.com/79074/71785884-bdeb6f80-2fb9-11ea-8741-2c574957a34e.png)

![image](https://user-images.githubusercontent.com/79074/71785886-c2178d00-2fb9-11ea-8208-98dd52e645ce.png)

![image](https://user-images.githubusercontent.com/79074/71785887-c5ab1400-2fb9-11ea-874e-bf7c3bac24e5.png)

This appears widespread and has been discussed in the #bugs channel.

**Comment by conlan** [comment]
So it's definitely fixed for some areas:

<img width="547" alt="Screen Shot 2020-01-09 at 1 47 30 PM" src="https://user-images.githubusercontent.com/79074/72107763-e095c500-32e6-11ea-821f-766e82660448.png">

But looks to still be occurring in some places:

<img width="571" alt="Screen Shot 2020-01-09 at 1 46 52 PM" src="https://user-images.githubusercontent.com/79074/72107727-ccea5e80-32e6-11ea-8247-26f5c3edd1b5.png">

Seems that especially large gifs with many frames are the ones are affected^

**Comment by conlan** [comment]
Some users aren't seeing the above image but instead get the red and black checkerboard entirely: 
![image](https://user-images.githubusercontent.com/79074/72108306-21420e00-32e8-11ea-9574-26bec09dc1c6.png)

**Comment by bnolan** [comment]
Fixed I believe!
