### ISSUE TITLE
Point of view changes when using ui=html and clicking on "edit"

### ISSUE THREAD

**Issue by Bullauge** [cryptovoxels/issues#73]
Clicking on "edit" in ui=html mode sometimes changes your avatars point of view to the upper right which is slowing the building process (a lot) and which is confusing for new users.

![Cryptovoxels](https://user-images.githubusercontent.com/59541562/71786029-290f6300-3007-11ea-9af9-0aa70ff89889.gif)

**Comment by bnolan** [comment]
Is this something to do with when we release pointerlock and render the element, then focus it?

**Comment by bnolan** [comment]
The buggy code might be somewhere in `feature.ts` in the `editFeature` method - maybe in here?

```
    if (wantsHtml5() && f.constructor.Editor) {
      this.highlight()
      this.openEditor(f.constructor.Editor)
    } else {
      ui.show(f.edit())
    }
```

**Comment by bnolan** [comment]
Hey, we can't replicate this at the moment @Bullauge - are there some specific replication steps that cause it - or a particular browser?>

**Comment by Bullauge** [comment]
Hey Ben, i used Chrome on Windows 10. Placed images at wall. Than tried to
edit and pointer switched. Sometimes it works, sometimes not. Maybe place
images in all sky directions and try to edit via ui=html. I have the
feeling that sometimes the angle your avatar has to the image triggers the
bug.

Ben Nolan <notifications@github.com> schrieb am Fr. 31. Jan. 2020 um 00:02:

**Comment by bnolan** [comment]
Hey @moritree can you try and replicate this issue and show it to me?

**Comment by bnolan** [comment]
Fixed by being careful with focus() and blur()
