### ISSUE TITLE
Map has some missing parts

### ISSUE THREAD

**Issue by damo1884** [cryptovoxels/issues#8]
https://www.cryptovoxels.com/parcels/304
![image](https://user-images.githubusercontent.com/1332166/56483031-2d491f80-647c-11e9-93e0-b525c0acc7a8.png)

**Comment by bnolan** [comment]
Yup, map isn't generating for all parcels at the moment. I'll try and fix this quickly, but I think I need to move the map generation code onto amazon lambdas, it takes half an hour to generate on my macbook now, and is still missing parts of the map.

**Comment by damo1884** [comment]
@bnolan also why do only the parcels in the center show stuff built?

![image](https://user-images.githubusercontent.com/1332166/58928766-bb195b00-8708-11e9-91e4-16281e9cd794.png)

**Comment by bnolan** [comment]
Fixed, the view radius was too low.
