### ISSUE TITLE
Invisible voxels, transparent mesh

### ISSUE THREAD

**Issue by bnolan** [cryptovoxels/issues#88]
On @moritree's parcel - can't see any voxels - but they are collidable / pickable. Assuming the tileset hasn't loaded. Content is:

```
{"success":true,"parcel":{"id":282,"height":9,"token":null,"colors":0,"name":null,"address":"2 Blade Court","geometry":{"type":"Polygon","coordinates":[[[1.38,0.97],[1.26,0.97],[1.26,1.1],[1.38,1.1],[1.38,0.97]]]},"area":156,"streets":[{"id":32,"name":"Login Alley","geometry":"0102000020110F0000020000007B14AE47E17AE43F676666666666EE3F48E17A14AE470340676666666666EE3F","visible":true},{"id":109,"name":"Grim Arcade","geometry":"0102000020110F0000020000001F85EB51B81EF53F00000000000000001F85EB51B81EF53F676666666666EE3F","visible":true},{"id":756,"name":"Blade Court","geometry":"0102000020110F000002000000676666666666F63F676666666666EE3F676666666666F63FF6285C8FC2F5F43F","visible":true},{"id":1327,"name":"Electra Road","geometry":"0102000020110F0000020000003E0AD7A3703DF23FEC51B81E85EBF13F676666666666F63FEC51B81E85EBF13F","visible":true}],"distance":159.012578118839,"x1":126,"x2":138,"y1":0,"y2":9,"z1":97,"z2":110,"suburb":"North Terrace","traffic_visits":"99","owner":"0xd1f471f3828083d920273f67590e4a25463d22ff","owner_name":"moritree","contributors":null,"images":null,"description":null,"sandbox":false,"price":0,"content":{"voxels":"eJzt3EEKwkAQRNEEL+7RJYySjUhmJE3RvO8mmwK7yKehF9mfe8lve3P1adseC5mTuzOr86fOs5LRQV0HNZZ+7+M3p6eJzE20Mn8+OvivA57ej3dUBwc85Wk6Oujn6fw8j4XMWm8yMrWZeXMSLR3Yp+nooN8+nZlmwNN0dMBTnuajA57yNB8d9PPUHUlGxh2pGrtEBwfd9unMNAOepqMDnvI0Hx3wlKf56KCfp+5IMjLuSNXYJTo46LZPZ6YZ8DQdHfCUp/nooK+n1/+b7zmkZ3RQ10G1p9fJ3qdAJbmeAvjAUyAfngL58BTI5wWnzJRw","features":[],"settings":{},"tileset":"/uploads/atlas-1582169754874.png","palette":["#ffffff","#888888","#000000","#ff71ce","#01cdfe","#05ffa1","#b967ff","#fffb96"]}}}
```

**Comment by bnolan** [comment]
Ok - this is because the tileset serving is totally broken.

Tasks:

* Strip metadata and hash all the tilesets - find out how many unique ones we have
* Move unique tilesets onto s3
* Write a job to rewrite all the `tileset` data in the database with the correct new hashed address, null out all the tilesets that are just the default tileSets
* Dangerously mutate the entire world (back up database and check with community first)
* Delete the tileset editor because it's stupid and broken, make it so you can just drag and drop from the desktop into the tiles menu at the bottom of the html UI
* Work out how we increase from 16 tiles to 64 tiles, and duplicate the tiles 4x when sticking them in the atlas so we don't have to do the stupid `pow()` trick in the fragment shader to prevent incorrect mip map level lookups (talk to nick or ben about this)

**Comment by damo1884** [comment]
If you had a library of tiles you could increase the usage of the same small set of tile images.

**Comment by bnolan** [comment]
Fixed!
