### ISSUE TITLE
NFTs disappear when leaving the parcel

### ISSUE THREAD

**Issue by Benjythebee** [cryptovoxels/issues#98]
**Describe the bug**
Cubic reports that multiple features (NFTs) disappeared after refreshing and also after "looking away" and leaving the parcel.

**To Reproduce**
According to Cubic, you'd:
- create an NFT
- leave the parcel
- item disappeared

I'll add more information once Cubic replies.

**Expected behavior**
NFTs/images should stay where they have been placed and not disappear.

**Screenshots**

![image](https://user-images.githubusercontent.com/38708022/84568286-6a841580-add2-11ea-9054-bd1f89317dad.png)

**Desktop :**
 - OS: Linux
 - Browser: Brave, chromium
 - Version 1.9.80 Chromium: 81.0.4044.138 (Official Build) (64-bit)

**Comment by mmckegg** [comment]
@Benjythebee Did you hear anything more about this issue?

**Comment by Benjythebee** [comment]
No, I'm closing because I think it was related to the image server and I haven't heard anyone with the same problem
